# Generated by Django 4.0.2 on 2022-04-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
