# Generated by Django 4.0.2 on 2022-04-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0003_alter_ticket_slot_allotted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('Parked', 'Parked'), ('Departed', 'Departed')], default='Parked', max_length=25),
        ),
    ]
