# Generated by Django 4.0.2 on 2022-04-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0004_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
